In [2]:
import sklearn
import numpy
print("scikit-learn version:", sklearn.__version__)
print("Installation successful!")

scikit-learn version: 1.8.0
Installation successful!


In [3]:
#word embedding
from sklearn.feature_extraction.text import CountVectorizer
corpus = ["We have the DTS406TC course", "NLP is useful", "we have learned deep learning algorithms"]
vectorizer = CountVectorizer()
result = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(result.toarray())

vectorizer = TfidfVectorizer()
result = vectorizer.fit_transform(["We have the DTS406TC course", "NLP is useful", "we have learned deep learning algorithms"])
print(vectorizer.get_feature_names_out())
print(result.toarray())

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

texts = ["I love NLP", "Python is easy to learn", "I hate bugs", "Coding is fun", "Machine learning is important"]
labels = [1, 1, 0, 1, 1]  
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)

# Split data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2)

# Train Logistic Regression
model = LogisticRegression()
model.fit(X_train, y_train)

# Predictions
predictions = model.predict(X_test)
print(predictions)

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predictions)
print("Confusion Matrix:\n", cm)

from sklearn.metrics import confusion_matrix
y_test = [1, 0, 1, 0]
predictions = [1, 0, 1, 1]
cm = confusion_matrix(y_test, predictions)
print("Confusion Matrix:\n", cm)






['algorithms' 'course' 'deep' 'dts406tc' 'have' 'is' 'learned' 'learning'
 'nlp' 'the' 'useful' 'we']
[[0 1 0 1 1 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 0 0 1 0 1 0]
 [1 0 1 0 1 0 1 1 0 0 0 1]]


NameError: name 'TfidfVectorizer' is not defined